#pragma once

#include <memory>
#include <string>
#include <vector>

#include "hardware_interface/handle.hpp"
#include "hardware_interface/hardware_info.hpp"
#include "hardware_interface/system_interface.hpp"
#include "hardware_interface/types/hardware_interface_return_values.hpp"
#include "rclcpp_lifecycle/state.hpp"

#include "epos4/core/UnitConversion.hpp"
#include "epos4/hardware/Epos4.hpp"

namespace epos4_ros2_control
{

// ---------------------------------------------------------------------------
// ros2_control SystemInterface for a CAN bus of maxon EPOS4 drives.
//
// One instance owns one bus and one Epos4 per joint. Commands go out as
// Cyclic Synchronous Position: the trajectory is generated by the controller
// and the drive interpolates between the setpoints it receives, which is the
// model joint_trajectory_controller assumes.
//
//   command interfaces:  position
//   state interfaces:    position, velocity, effort
//
// Everything is in RADIANS at the joint, as ros2_control expects. The
// conversion to encoder counts uses epos4::MechanismScale, configured per
// joint from the URDF.
//
// read() and write() touch no bus. Inbound PDOs land in atomics on the
// CANopen thread and setpoints are published there on SYNC, so the control
// loop only ever does relaxed atomic loads and stores. See the cyclic path
// section of epos4/hardware/Epos4.hpp for why that matters.
// ---------------------------------------------------------------------------
class Epos4System : public hardware_interface::SystemInterface
{
public:
  hardware_interface::CallbackReturn on_init(
    const hardware_interface::HardwareInfo & info) override;

  hardware_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;

  hardware_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;

  hardware_interface::CallbackReturn on_deactivate(
    const rclcpp_lifecycle::State & previous_state) override;

  hardware_interface::CallbackReturn on_cleanup(
    const rclcpp_lifecycle::State & previous_state) override;

  std::vector<hardware_interface::StateInterface> export_state_interfaces() override;
  std::vector<hardware_interface::CommandInterface> export_command_interfaces() override;

  hardware_interface::return_type read(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

  hardware_interface::return_type write(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

private:
  // One per joint. The Epos4 is held by pointer because it is neither
  // copyable nor movable: it registers itself with the bus on construction.
  struct Axis
  {
    std::string name;
    std::uint8_t nodeId{0};
    epos4::MechanismScale scale;
    std::unique_ptr<epos4::Epos4> device;

    // Handed to ros2_control by address, so these must not move once the
    // interfaces are exported. The vector is sized once in on_init.
    double statePosition{0.0};   // rad
    double stateVelocity{0.0};   // rad/s
    double stateEffort{0.0};     // Nm
    double commandPosition{0.0};  // rad

    // Rated torque, read once when configuring, for the effort interface.
    // Zero means the motor data was never set, and effort stays at zero
    // rather than reporting a number scaled by an unknown.
    std::uint32_t ratedTorqueMicroNm{0};
  };

  std::vector<Axis> axes_;
  std::unique_ptr<epos4::CanBus> bus_;

  std::string canInterface_;
  std::string masterDcf_;
  std::uint8_t masterNodeId_{1};

  // Logged once rather than every cycle: a bus that has gone quiet would
  // otherwise produce a message per axis per cycle and bury everything else.
  bool unhealthyReported_{false};
};

}  // namespace epos4_ros2_control
